### ISSUE TITLE
Can't install word_wrap 1.0.0 on mac

### ISSUE THREAD

**Issue by cedoucette** [pazdera/word_wrap#8]
I tried this:
 sudo gem install -V --debug word_wrap

NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:171 - LoadError
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=word_wrap
200 OK
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.hegn.us
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.pubedu.hegn.us
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.ad.hmco.com
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.rpcsys.hmco.com
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.rvdp.riverdeep.net
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.riverdeep.net
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.harcourtbrace.com
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.hmco.com
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.harcourt.com
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.hmhpub.com
Exception `Resolv::DNS::Config::NXDomain' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.hmhco.com
Exception `Resolv::ResolvError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/resolv.rb:494 - DNS result has no information for _rubygems._tcp.api.rubygems.org
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/quick/Marshal.4.8/word_wrap-1.0.0.gemspec.rz
200 OK
GET https://api.rubygems.org/quick/Marshal.4.8/word_wrap-1.0.0.gemspec.rz
200 OK
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/specifications/word_wrap-1.0.0.gemspec
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/.gitignore
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/.gitignore
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/.gitignore
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/.gitignore
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/Gemfile
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/Gemfile
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/Gemfile
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/Gemfile
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/LICENSE.txt
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/LICENSE.txt
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/LICENSE.txt
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/LICENSE.txt
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/README.md
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/README.md
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/README.md
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/README.md
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/Rakefile
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/Rakefile
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/Rakefile
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/Rakefile
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/bin/ww
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/bin/ww
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/bin/ww
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/bin/ww
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap.rb
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap.rb
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/core_ext.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/core_ext.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/core_ext.rb
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/core_ext.rb
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/version.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/version.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/version.rb
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/version.rb
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/wrapper.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/wrapper.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/wrapper.rb
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/lib/word_wrap/wrapper.rb
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/spec/core_ext_spec.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/spec/core_ext_spec.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/spec/core_ext_spec.rb
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/spec/core_ext_spec.rb
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/spec/ww_spec.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/spec/ww_spec.rb
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/spec/ww_spec.rb
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/spec
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/spec/ww_spec.rb
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/word_wrap.gemspec
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1331 - No such file or directory @ rb_file_s_lstat - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/word_wrap.gemspec
Exception `Errno::ENOENT' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/word_wrap.gemspec
Exception `Errno::EEXIST' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0
/usr/local/lib/ruby/gems/2.3.0/gems/word_wrap-1.0.0/word_wrap.gemspec
Exception `NoMethodError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/package/tar_reader.rb:72 - undefined method `seek' for #<Zlib::GzipReader:0x007ffe6a297410>
Exception `TypeError' at /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/installer.rb:227 - no implicit conversion of nil into String
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/installer.rb:227:in `check_executable_overwrite'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/installer.rb:468:in `block in generate_bin'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/installer.rb:455:in `each'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/installer.rb:455:in `generate_bin'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/installer.rb:295:in `install'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/request_set.rb:167:in `block in install'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/request_set.rb:151:in `each'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/request_set.rb:151:in `install'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/commands/install_command.rb:250:in `install_gem'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/commands/install_command.rb:300:in `block in install_gems'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `each'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/commands/install_command.rb:296:in `install_gems'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/commands/install_command.rb:203:in `execute'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/command.rb:308:in `invoke_with_build_args'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
	/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
	/usr/local/bin/gem:21:in `<main>'

**Comment by cedoucette** [comment]
When I listed the contents of the ruby installer, I see these lines which may be relevant
(in this file: /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/installer.rb):

```
  221      # somebody has written to RubyGems' directory, overwrite, too bad
   222      return if Gem.default_bindir != @bin_dir and not ruby_executable
   223  
   224      question = "#{spec.name}'s executable \"#{filename}\" conflicts with "
   225  
   226      if ruby_executable then
   227        question << existing
   228  
   229        return if ask_yes_no "#{question}\nOverwrite the executable?", false
   230  

```
